"""Place the runtime-proven P8 artifacts generated by current modules."""
from __future__ import annotations

from pathlib import Path

from .battle_adapters import build_dispatch, build_width
from .battle_assets import build as build_battle_assets
from .battle_contract import BattleContract
from .battle_renderer import build as build_battle_renderer
from .battle_stock_fb import build as build_battle_stock_fb


ROOT = Path(__file__).resolve().parents[2]
BATTLE_CONTRACT = ROOT / "data" / "config" / "battle-contract.json"


def place_current_battle(image: bytes, clean_image: bytes) -> tuple[bytes, dict]:
    """Place P8 assets, code, adapters and hooks with contract verification."""
    contract = BattleContract.load(BATTLE_CONTRACT)
    contract.verify_clean(clean_image)
    payload = bytearray(image)
    assets, asset_addresses = build_battle_assets(contract)
    for name, artifact in assets.items():
        at = asset_addresses[name]
        payload[at:at + len(artifact)] = artifact
    renderer = build_battle_renderer(contract)
    payload[contract.renderer_pc:contract.renderer_pc + len(renderer)] = renderer
    generated = {
        "stock_fb": lambda spec: build_battle_stock_fb(spec),
        "width": lambda spec: build_width(spec.cpu, spec.dependency_cpu),
        "dispatch": lambda spec: build_dispatch(spec.cpu, spec.dependency_cpu),
    }
    for adapter in contract.adapters:
        actual = generated[adapter.id](adapter)
        if len(actual) != adapter.bytes:
            raise ValueError(f"current {adapter.id} size differs from its contract")
        payload[adapter.pc:adapter.pc + len(actual)] = actual
    for hook in contract.hooks:
        payload[hook.pc:hook.pc + len(hook.proven)] = hook.proven
    final = bytes(payload)
    contract.verify_proven(final)
    return final, {
        "owner": "current modules",
        "assets": len(assets),
        "renderer_bytes": len(renderer),
        "adapters": [adapter.id for adapter in contract.adapters],
        "hooks": [hook.id for hook in contract.hooks],
    }
