"""BDF export and import, so the glyphs can be checked in a font editor.

BDF is the one bitmap-font format every editor reads. Exporting the atlas to it
means the proof sheet is not the only way to look at the glyphs: they can be
opened, measured and corrected in a real editor, and the corrections brought
back as overrides.

Cluster and icon glyphs go in the private use area, because they are not single
Unicode characters. Latin, digits and punctuation keep their own codepoints, so
they show up where an editor expects them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

CELL_WIDTH = 8
CELL_ROWS = 16
FONT_ASCENT = 13
FONT_DESCENT = CELL_ROWS - FONT_ASCENT
PUA_BASE = 0xE000


@dataclass(frozen=True)
class BdfGlyph:
    token: str
    codepoint: int
    advance: int
    rows: tuple[int, ...]


def codepoint_for(token: str, index: int) -> int:
    """A real codepoint for single characters, private use for everything else."""
    kind, value = token.split(":", 1)
    if kind == "char" and len(value) == 1:
        return ord(value)
    return PUA_BASE + index


def safe_name(token: str) -> str:
    """A BDF-safe STARTCHAR name that still says which token it is."""
    kind, value = token.split(":", 1)
    body = "".join(
        char if char.isascii() and char.isalnum() else f"u{ord(char):04X}"
        for char in value
    )
    return f"{kind}_{body or 'space'}"


def write(glyphs: list[BdfGlyph], *, note: str) -> str:
    lines = [
        "STARTFONT 2.1",
        f"COMMENT {note}",
        "COMMENT Generated by tools/export_font.py -- edit in a font editor, then",
        "COMMENT bring changes back with tools/import_font.py",
        "FONT -srw4-thai-medium-r-normal--16-160-72-72-c-80-iso10646-1",
        "SIZE 16 72 72",
        f"FONTBOUNDINGBOX {CELL_WIDTH} {CELL_ROWS} 0 -{FONT_DESCENT}",
        "STARTPROPERTIES 4",
        f"FONT_ASCENT {FONT_ASCENT}",
        f"FONT_DESCENT {FONT_DESCENT}",
        "DEFAULT_CHAR 32",
        "SPACING \"P\"",
        "ENDPROPERTIES",
        f"CHARS {len(glyphs)}",
    ]
    for glyph in glyphs:
        lines += [
            f"STARTCHAR {safe_name(glyph.token)}",
            f"ENCODING {glyph.codepoint}",
            "SWIDTH 500 0",
            f"DWIDTH {glyph.advance} 0",
            f"BBX {CELL_WIDTH} {CELL_ROWS} 0 -{FONT_DESCENT}",
            "BITMAP",
        ]
        lines += [f"{row:02X}" for row in glyph.rows]
        lines.append("ENDCHAR")
    lines.append("ENDFONT")
    return "\n".join(lines) + "\n"


class BdfError(ValueError):
    """The file is not a BDF this project can read back."""


def read(text: str) -> dict[int, BdfGlyph]:
    """Parse a BDF into codepoint -> glyph. Only what we wrote out is supported."""
    glyphs: dict[int, BdfGlyph] = {}
    name = None
    codepoint = None
    advance = None
    rows: list[int] | None = None

    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("STARTCHAR"):
            name = line.split(None, 1)[1] if " " in line else ""
            codepoint = advance = None
            rows = None
        elif line.startswith("ENCODING"):
            codepoint = int(line.split()[1])
        elif line.startswith("DWIDTH"):
            advance = int(line.split()[1])
        elif line == "BITMAP":
            rows = []
        elif line == "ENDCHAR":
            if codepoint is None or rows is None:
                raise BdfError(f"glyph {name!r} is missing its encoding or bitmap")
            if len(rows) != CELL_ROWS:
                raise BdfError(f"glyph {name!r} has {len(rows)} rows, expected {CELL_ROWS}")
            glyphs[codepoint] = BdfGlyph(
                token=name or "",
                codepoint=codepoint,
                advance=advance if advance is not None else CELL_WIDTH,
                rows=tuple(rows),
            )
            rows = None
        elif rows is not None:
            if not re.fullmatch(r"[0-9A-Fa-f]{2,4}", line):
                raise BdfError(f"glyph {name!r} has a bad bitmap row: {line!r}")
            # Rows wider than one byte are padded on the right; we only use 8px.
            glyphs_row = int(line[:2], 16)
            rows.append(glyphs_row)

    if not glyphs:
        raise BdfError("no glyphs found in the file")
    return glyphs
